version: 2
updates:
  - package-ecosystem: npm
    directory: /SmartProBonoPocket
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps-mobile

  - package-ecosystem: npm
    directory: /web-next
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps-web
